### ISSUE TITLE
wallpaper 1.1.3 package is not working with flutter 3.29

### ISSUE THREAD

**Issue by Neelam1990** [pratiktimer/setWallpaperplugin#32]
After upgrading flutter to the latest version, i.e. 3.29, the wallpaper package is showing an error like the following.

\wallpaper-1.1.3\android\src\main\java\com\prateektimer\wallpaper\WallpaperPlugin.java:51: error: cannot find symbol
    public static void registerWith(io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                                           ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.

Can anyone assist me in resolving this?

**Comment by pratiktimer** [comment]
check with latest 1.1.4
